version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: temphora-app
    ports:
      - "4000:4000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/dist              
    env_file:
      - .env
    restart: unless-stopped
    command: npm run ${NODE_ENV_SCRIPT}